name: Sphinx build

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**/README.md'
      - 'docs/**'
  push:
    branches: [ main, dev ]
    paths:
      - '**/README.md'
      - 'docs/**'
# later, allow only main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: pip install --upgrade pip poetry

      - name: Dependencies
        run: poetry install --with docs

      - name: Build HTML
        run: |
          cd docs
          poetry run make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        #        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
